# Generated by Django 2.1.7 on 2019-02-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190226_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='password_open',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
