# Generated by Django 2.1.7 on 2019-02-27 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190226_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoginInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeUID', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
